// Code generated by MockGen. DO NOT EDIT.
// Source: fund.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "balance_avito/internal/models"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// AcceptPayment mocks base method.
func (m *MockDatabase) AcceptPayment(ctx context.Context, reservation models.Reservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptPayment", ctx, reservation)
	ret0, _ := ret[0].(error)
	return ret0
}

// AcceptPayment indicates an expected call of AcceptPayment.
func (mr *MockDatabaseMockRecorder) AcceptPayment(ctx, reservation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptPayment", reflect.TypeOf((*MockDatabase)(nil).AcceptPayment), ctx, reservation)
}

// Accrue mocks base method.
func (m *MockDatabase) Accrue(ctx context.Context, accrual models.Accrual) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Accrue", ctx, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// Accrue indicates an expected call of Accrue.
func (mr *MockDatabaseMockRecorder) Accrue(ctx, accrual interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Accrue", reflect.TypeOf((*MockDatabase)(nil).Accrue), ctx, accrual)
}

// GetBalance mocks base method.
func (m *MockDatabase) GetBalance(ctx context.Context, account models.Account) (models.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, account)
	ret0, _ := ret[0].(models.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockDatabaseMockRecorder) GetBalance(ctx, account interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockDatabase)(nil).GetBalance), ctx, account)
}

// RejectPayment mocks base method.
func (m *MockDatabase) RejectPayment(ctx context.Context, reservation models.Reservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectPayment", ctx, reservation)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectPayment indicates an expected call of RejectPayment.
func (mr *MockDatabaseMockRecorder) RejectPayment(ctx, reservation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectPayment", reflect.TypeOf((*MockDatabase)(nil).RejectPayment), ctx, reservation)
}

// Reservation mocks base method.
func (m *MockDatabase) Reservation(ctx context.Context, reservation models.Reservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reservation", ctx, reservation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reservation indicates an expected call of Reservation.
func (mr *MockDatabaseMockRecorder) Reservation(ctx, reservation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reservation", reflect.TypeOf((*MockDatabase)(nil).Reservation), ctx, reservation)
}
