version: '3.7'

services:
  db:
    container_name: "balance_db"
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "avito"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "usersbalance"
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name:  "balance_avito"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "1323:1323"
    depends_on:
      - db
    volumes:
      - .:/app/

networks:
  default:
volumes:
  mysql_data: