package main

import (
	"log"

	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"

	_ "balance_avito/docs" // docs are generated by Swag CLI

	"balance_avito/internal/handlers/fund_handlers"
	"balance_avito/internal/handlers/report_handlers"
	"balance_avito/internal/infrastructure/echo_framework/fund_echo"
	"balance_avito/internal/infrastructure/echo_framework/report_echo"
	gocsv_adapter "balance_avito/internal/infrastructure/gocsv/adapter"
	"balance_avito/internal/infrastructure/sql_database/adapter"
)

// @title       Microservice for balance management
// @version     1.0
// @description Avito backend test task

// @contact.name Strykanova Vera
// @contact.url  https://tlgg.ru/verastryka

// @host     localhost:1323
// @BasePath /

func main() {
	db, err := adapter.RunDB()
	if err != nil {
		log.Fatal(err)
	}

	dbAdapter := adapter.NewDatabaseAdapter(db)
	goCSVAdapter := gocsv_adapter.NewGoSCVAdapter()

	fund := fund_handlers.NewFund(dbAdapter)
	report := report_handlers.NewReport(dbAdapter, goCSVAdapter)

	fundHandler := fund_echo.NewFundHandler(fund)
	reportHandler := report_echo.NewReportHandler(report)

	e := echo.New()

	fundRouter := e.Group("/fund")
	fundRouter.POST("/accrual", fundHandler.Accrue)
	fundRouter.POST("/reservation", fundHandler.Reservation)
	fundRouter.POST("/payment_acceptance", fundHandler.AcceptPayment)
	fundRouter.POST("/payment_rejection", fundHandler.RejectPayment)
	fundRouter.GET("/balance", fundHandler.GetBalance)

	reportRouter := e.Group("/report")
	reportRouter.GET("/accounting", reportHandler.Accounting)
	reportRouter.GET("/transactions_history", reportHandler.TransactionsHistory)

	e.GET("/swagger/*", echoSwagger.WrapHandler)

	e.Logger.Fatal(e.Start(":1323"))
}
